package com.random.mapper;

import com.random.domain.Sc;
import java.util.List;

public interface ScMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbggenerated Tue Jul 24 17:42:07 CST 2018
     */
    int insert(Sc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbggenerated Tue Jul 24 17:42:07 CST 2018
     */
    List<Sc> selectAll();
}