package com.random.mapper;

import com.random.domain.Teacher;
import java.util.List;

public interface TeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Tue Jul 24 17:42:07 CST 2018
     */
    int deleteByPrimaryKey(String teacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Tue Jul 24 17:42:07 CST 2018
     */
    int insert(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Tue Jul 24 17:42:07 CST 2018
     */
    Teacher selectByPrimaryKey(String teacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Tue Jul 24 17:42:07 CST 2018
     */
    List<Teacher> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Tue Jul 24 17:42:07 CST 2018
     */
    int updateByPrimaryKey(Teacher record);
}